server:
  port: 8080

#management:
#  endpoint:
#    shutdown:
#      enabled: true
#    beans:
#      enabled: true
#    env:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "shutdown,beans,env,info,health"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %replace(%m){'([\\|])','\\$1'}%n%wEx"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{15}){cyan}  [%clr(%X{cx}){blue}] %clr(:){faint} %replace(%m){'([\\|])','\\$1'}%n%wEx"
  file:
    name: cx-flow.log

#  level:
#    com:
#      checkmarx:
#        flow:
#          service: info
#          utils: info
#    org:
#      apache:
#        http:
#          wire: TRACE
#      springframework:
#        web:
#          client:
#            RestTemplate: TRACE

cx-flow:
  bug-tracker: Json
  bug-tracker-impl:
    - CxXml
    - Json
    - GitHub
    - Csv
    - Sarif
    - Json
  filter-severity:
    - High
    - Medium
    - Low
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  zip-exclude: ""
  break-build: false
  enabled-vulnerability-scanners: ast

json:
  file-name-format: "cx.json"
  data-folder: "/tmp"

cx-xml:
  file-name-format: "cx.xml"
  data-folder: "/tmp"

csv:
  file-name-format: "cx.csv"
  data-folder: "/tmp"
  include-header: true
  fields:
    - header: Application
      name: application
      default-value: unknown
    - header: file
      name: filename
    - header: Vulnerability Name
      name: category
    - header: CWE
      name: cwe
    - header: Severity
      name: severity
    - header: Similarity ID
      name: similarity-id

