description: >
  Select version of CxFlow to use.  Any available tag from this list can be used: https://hub.docker.com/r/checkmarx/cx-flow/tags
docker:
  - image: 'checkmarx/cx-flow:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: >
      Pick a specific checkmarx/cx-flow image variant:
      https://hub.docker.com/r/checkmarx/cx-flow/tags
    type: string
